Update HTTPoison to 1.0
svileng/stripy pull request #5
Opened 2018-04-17 23:46 UTC by toddholmberg

HTTPoison 0.13 version requirement conflicts with apps using HTTPoison 1.0.

2018-05-16 16:34 UTC, svileng requested changes
Sorry for the delay — please see my comment below.

2018-05-16 16:34 UTC, svileng commented on mix.exs
> +    [{:httpoison, "~> 1.0"},
Let's make this `~> 0.13 or ~> 1.0` for users still on HTTPoison 0.13.

2018-05-16 18:38 UTC, toddholmberg commented on mix.exs
> +    [{:httpoison, "~> 1.0"},
@svileng Is it possible to use a conditional in the deps list?

2018-05-17 14:26 UTC, svileng commented on mix.exs
> +    [{:httpoison, "~> 1.0"},
@toddholmberg Yes. https://github.com/appsignal/appsignal-elixir/blob/develop/mix.exs#L92

2018-12-03 02:32 UTC, ddorosz commented
Is there still any plan to implement the conditional dependency?

2018-12-03 11:53 UTC, svileng commented
@ddorosz I haven't heard from @toddholmberg so feel free to send a PR (it's a super small change). Alternatively I will try to do it soon-ish.

2018-12-05 15:29 UTC, svileng commented
Released as part of `1.2.1` 🎉

2018-12-05 15:29 UTC, closed without merging